### PR TITLE
Possible fix for heroku deployment

### PR DESCRIPTION
**Pull request by Dylanb-dev**
I made a couple of changes to make the app deployable on heroku as it gave an error before.

I'm very novice with webpack and with the process.env.PRODUCTION variable so my solution is probably incorrect.

### CODE REVIEW

**Comment by pheuter** [comment]
Yeah, master is currently working towards release v0.4.0 which is still a WIP. One of the things left to do is to make sure the Heroku button still works. I believe the latest issue is around not installing node devDependencies, which currently are required to build the app.

I don't think a Procfile is necessary for a Heroku button deploy, should be as simple as setting configuration in the `app.json` file to install all node modules.

**Comment by Dylanb-dev** [comment]
Didn't mean to close this, I have made the modification to app.json.

**Comment by pheuter** [comment]
sweet, thanks! has this been tested in a sample deploy?

**Comment by Dylanb-dev** [comment]
Yes, pressing the deploy button on my fork deployed with no errors.
Result: https://er-deploy-fix.herokuapp.com/

**Comment by pheuter** [comment]
:+1:

**Pull request merged**
